# Generated by Django 5.1 on 2024-09-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Opportunities", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opportunities",
            old_name="cc",
            new_name="CC",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="class_mode",
            new_name="Class_Mode",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="description",
            new_name="Description",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="email",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="fee_coated",
            new_name="Fee_Quoted",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="lead_source",
            new_name="Lead_Source",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="lead_status",
            new_name="Lead_Status",
        ),
        migrations.RenameField(
            model_name="opportunities",
            old_name="contact_no",
            new_name="Phone",
        ),
        migrations.RemoveField(
            model_name="opportunities",
            name="courses",
        ),
        migrations.RemoveField(
            model_name="opportunities",
            name="datetime",
        ),
        migrations.RemoveField(
            model_name="opportunities",
            name="stack",
        ),
        migrations.AddField(
            model_name="opportunities",
            name="Course",
            field=models.CharField(
                choices=[
                    ("HR Generalist core HR", "HR Generalist core HR"),
                    ("HR Analytics", "HR Analytics"),
                    ("Spoken English", "Spoken English"),
                    ("Public Speaking", "Public Speaking"),
                    ("Communication Skills", "Communication skills"),
                    ("Soft Skills", "Soft Skills"),
                    ("Personality Development", "Personality Development"),
                    ("IELTS", "IELTS"),
                    ("TOEFL", "TOEFFL"),
                    ("PTE", "PTE"),
                    ("GRE", "GTE"),
                    ("GMAT", "GMAT"),
                    ("Recruitment Specialist", "Recruitment Specialist"),
                    ("Payroll Specialist", "Payroll Specialist"),
                    ("Learning and Development", "Learning and Development"),
                    ("Others", "Others"),
                    ("Finance", "Finance"),
                    ("Competitive Exams", "Competitive Exams"),
                    ("HR Manager", "HR Manager"),
                ],
                default="None",
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="opportunities",
            name="Lost_Opportunity_Reason",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Invalid Number", "Invalid Number"),
                    ("Not Interested", "Not Interested"),
                    ("Joined another institute", "Joined another institute"),
                    ("Asking free course", "Asking free course"),
                    ("Pay after palcement", "Pay after placement"),
                ],
                default="Select Lost Opportunity Reason",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="opportunities",
            name="Opportunity_Status",
            field=models.CharField(
                choices=[
                    ("Select Opportunity Status", "Select Opportunity Status"),
                    ("visiting", "visiting"),
                    ("visited", "visited"),
                    ("Demo attended", "Demo attended"),
                ],
                default="Select Opportunity Status",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="opportunities",
            name="Visited_Stage",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Call not answered", "Call not answered"),
                    ("Ready to join", "Ready to join"),
                    ("Fees Negotiation", "Fees Negotiation"),
                    ("Batch allocation", "Batch allocation"),
                    ("Interested Demo", "Interested Demo"),
                    ("Need time this week", "Need time this week"),
                    ("Need time next week", "Need time next week"),
                    ("Need time this Month", "Need time this Month"),
                    ("Need time Next Month", "Need time Next Month"),
                    ("Special Requirment", "Speceial Requirement"),
                    ("Closed Won(Registered)", "Closed Won(Registered)"),
                    ("Closed Lost(Cold Lead)", "Closed Lost(Cold Lead)"),
                ],
                default="Select Visited Stage",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="opportunities",
            name="Stack",
            field=models.CharField(
                choices=[
                    ("Life Skills", "Life Skills"),
                    ("Study Abroad", "Study Abroad"),
                    ("HR", "HR"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
