# Generated by Django 5.1 on 2024-09-12 03:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leadmodules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="cc",
            field=models.BigIntegerField(default=91),
        ),
        migrations.AddField(
            model_name="leads",
            name="class_mode",
            field=models.CharField(
                choices=[
                    ("HYDClassRoom", "HYDClassRoom"),
                    ("BLRClassRoom", "BLRClassRoom"),
                    ("IndiaOnline", "IndiaOnline"),
                    ("InternationalOnline", "InternationalOnline"),
                ],
                default="HYDclassrrom",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="courses",
            field=models.CharField(
                choices=[
                    ("Angulaar", "Angulaar"),
                    ("AWS", "AWS"),
                    ("AWSWithDevOps", "AWSWithDevOps"),
                    ("Azure", "Azure"),
                    ("AzureDevOps", "AzureDevOps"),
                    ("BusinessAnlayst", "BusinessAnlayst"),
                    ("CloudOpsMasters", "CloudOpsMasters"),
                    ("DevOps", "DevOps"),
                    ("FrontEndAngular", "FrontEndAngular"),
                    ("FrontEndReact", "FrontEndReact"),
                    ("FullStackJAVA", "FullStackJAVA"),
                    ("FullStackMEAN", "FullStackMEAN"),
                    ("FullStackMERN", "FullStackMERN"),
                    ("FullstackPython", "FullstackPython"),
                    ("FullStackReactJAVA", "FullStackReactJAVA"),
                    ("Java", "Java"),
                    ("NeedCounselling", "NeedCounselling"),
                    ("Others", "Others"),
                    ("PowerBI", "PowerBI"),
                    ("Python", "Python"),
                    ("React", "React"),
                    ("SalesForceAdmin", "SalesForceAdmin"),
                    ("SalesforceDeveloper", "SalesforceDeveloper"),
                    ("ServiceNow", "ServiceNow"),
                    ("AzureDataEngineer", "AzureDataEngineer"),
                    ("Tableau", "Tableau"),
                    ("Testing", "Testing"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="datefield",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="leads",
            name="description",
            field=models.TextField(default="N/A", max_length=300),
        ),
        migrations.AddField(
            model_name="leads",
            name="email",
            field=models.EmailField(default="N/A", max_length=254),
        ),
        migrations.AddField(
            model_name="leads",
            name="fee_coated",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="leads",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("WalkIn", "WalkIn"),
                    ("StudentReferral", "StudentReferral"),
                    ("Demo", "Demo"),
                    ("WebSite", "WebSite"),
                    ("WebsiteChat", "WebsiteChat"),
                    ("InboundCall", "InboundCall"),
                    ("GoogleAdWords", "GoogleAdWords"),
                    ("FacebookAds", "FacebookAds"),
                    ("GoogleMyBusiness", "GoogleMyBusiness"),
                    ("WhatsAppDigitalLync", "WhatsAppDigitalLync"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="lead_status",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Not contacted", "Not contacted"),
                    ("Attempted", "Attempted"),
                    ("warm lead", "warm lead"),
                    ("opportunity", "opportunity"),
                    ("attendedemo", "attendedemo"),
                    ("visited", "visited"),
                    ("registered", "registered"),
                    ("coldlead", "coldlead"),
                ],
                default="None",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="leads",
            name="tech_stack",
            field=models.CharField(
                choices=[
                    ("CloudOps", "CloudOps"),
                    ("Salesforce", "Salesforce"),
                    ("FullStack", "FullStack"),
                    ("DataStack", "DataStack"),
                    ("ServiceNow", "ServiceNow"),
                    ("BusinessStack", "BusinessStack"),
                    ("CareerCounselling", "CareerCounselling"),
                ],
                default="None",
                max_length=20,
            ),
        ),
    ]
