# Generated by Django 5.1 on 2024-09-25 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leadmodules", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="leads",
            old_name="cc",
            new_name="CC",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="class_mode",
            new_name="Class_Mode",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="courses",
            new_name="Course",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="description",
            new_name="Description",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="email",
            new_name="Email",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="fee_coated",
            new_name="Fee_Quoted",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="lead_source",
            new_name="Lead_Source",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="lead_status",
            new_name="Lead_Status",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="user_name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="contact_no",
            new_name="Phone",
        ),
        migrations.RenameField(
            model_name="leads",
            old_name="tech_stack",
            new_name="Stack",
        ),
    ]
