# Generated by Django 5.1 on 2024-09-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leadmodules", "0002_rename_cc_leads_cc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leads",
            name="datefield",
        ),
    ]
