# Generated by Django 5.1.1 on 2024-09-27 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leads",
            name="Time",
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
