# Generated by Django 5.1.1 on 2024-09-27 12:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_leads_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leads",
            name="Time",
        ),
        migrations.AddField(
            model_name="leads",
            name="Datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
