# Generated by Django 5.1.1 on 2024-09-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Course_Image", models.ImageField(upload_to="")),
                ("Course_Name", models.CharField(max_length=200)),
                ("Course_Fee", models.DecimalField(decimal_places=2, max_digits=12)),
                ("Description", models.TextField(max_length=300)),
                ("Course_Brochure", models.ImageField(upload_to="")),
            ],
        ),
    ]
