# Generated by Django 5.1.1 on 2024-09-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0002_alter_course_course_brochure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Course_Image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
