# Generated by Django 5.1.1 on 2024-09-30 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Course", "0003_alter_course_course_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="Course_Brochure",
            field=models.FileField(upload_to="brochures/"),
        ),
    ]
